services:
  - type: web
    name: inventory-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run migrate:deploy && npm run seed:prod && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false
